import React from 'react'
import {Table,Row,Col} from '.'
import {Text} from 'react-native'

export function OrdersResults() {
    return (
      <Table headerTitle="Investigations Ordered and Results">
        <Row>
          <Col>
            <Col>
              <Text>Malaria</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>Microbiology</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>TB Test</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>Chemistry</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>Stool</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
          </Col>
  
          <Col>
            <Col>
              <Text>Hematology</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>X-Ray</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>Glucose</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>HIV</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>Urine</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Col>
              <Text>Other</Text>
            </Col>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
  
            <Row>
              <Col>
                <Text></Text>
              </Col>
              <Col>
                <Text>M</Text>
              </Col>
            </Row>
          </Col>
        </Row>
      </Table>
    );
  }
  